<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>TRL-PvpMode</AssemblyName>
    <Description>Mod de Respawn e Modo PVP para o Fika</Description>
    <Version>1.0.0</Version>
    <Authors>Umbigo Preto</Authors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- BepInEx & Harmony -->
    <Reference Include="BepInEx">
      <HintPath>References\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>References\0Harmony.dll</HintPath>
    </Reference>

    <!-- Tarkov & Unity -->
    <Reference Include="Assembly-CSharp">
      <HintPath>References\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>References\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>References\UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <!-- SPT & Utils -->
    <Reference Include="SPT.Reflection">
      <HintPath>References\SPT.Reflection.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>References\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>References\Sirenix.Serialization.dll</HintPath>
    </Reference>

    <!-- Fika Plugin -->
    <Reference Include="Fika.Core">
      <HintPath>References\Fika.Core.dll</HintPath>
    </Reference>

    <!-- Audio / VOIP -->
    <Reference Include="DissonanceVoip">
      <HintPath>References\DissonanceVoip.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
