<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Shared.props" />

  <PropertyGroup>
    <AssemblyName>7Bpencil.MaterialEditor.Fika</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaterialEditor\MaterialEditor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp" />
    <Reference Include="BepInEx" />
    <Reference Include="Comfort" />
    <Reference Include="Fika.Core" />
    <Reference Include="UnityEngine" />
    <Reference Include="UnityEngine.CoreModule" />
  </ItemGroup>

</Project>
