<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Shared.props" />

  <PropertyGroup>
    <AssemblyName>7Bpencil.EquipmentStickers</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeaponCamoAndStickers\WeaponCamoAndStickers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony" />
    <Reference Include="spt-reflection" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="BepInEx" />
    <Reference Include="Comfort" />
    <Reference Include="Sirenix.Serialization" />
    <Reference Include="UnityEngine" />
    <Reference Include="UnityEngine.AnimationModule" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="UnityEngine.InputLegacyModule" />
    <Reference Include="UnityEngine.IMGUIModule" />
    <Reference Include="UnityEngine.UI" />
    <Reference Include="UnityEngine.UIModule" />
  </ItemGroup>

</Project>
