<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>nexus-bundleloader</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>References\BepInEx.dll</HintPath></Reference>
    <Reference Include="UnityEngine"><HintPath>References\UnityEngine.dll</HintPath></Reference>
    <Reference Include="UnityEngine.AssetBundleModule"><HintPath>References\UnityEngine.AssetBundleModule.dll</HintPath></Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.CoreModule"><HintPath>References\UnityEngine.CoreModule.dll</HintPath></Reference>
  </ItemGroup>
</Project>