<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>hazelify.StanceSync</RootNamespace>
    <Nullable>disable</Nullable>
    <Authors>hazelify</Authors>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Configurations>Debug;Release</Configurations>
    <Version>$(AssemblyVersion)</Version>
    <LangVersion>latest</LangVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PhysicsModule">
      <HintPath>References\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>References\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="SPT.Common">
      <HintPath>References\SPT.Common.dll</HintPath>
    </Reference>
    <Reference Include="SPT.Reflection">
      <HintPath>References\SPT.Reflection.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>References\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>References\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>References\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="Comfort.Unity, Version=1.0.0.4, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>References\Comfort.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>References\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>References\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>References\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>References\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>References\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>References\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>References\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>References\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>References\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>References\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /y &quot;$(TargetPath)&quot; &quot;C:\SPT C\BepInEx\plugins\hazelify.$(TargetFileName)&quot;" />
  </Target>

  <Target Name="PackageModForDistribution" AfterTargets="Build">
    <PropertyGroup>
      <ModName>$(AssemblyName)</ModName>
      <ZipFileName>$(ModName).zip</ZipFileName>
      <TempPackageDir>$(ProjectDir)obj\Package</TempPackageDir>
      <ModPackageDir>$(TempPackageDir)\BepInEx\plugins</ModPackageDir>
    </PropertyGroup>
    <Message Text="--- Starting Mod packaging for distribution ---" Importance="high" />
    <RemoveDir Directories="$(TempPackageDir)" />
    <MakeDir Directories="$(ModPackageDir)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModPackageDir)" />
    <ZipDirectory SourceDirectory="$(TempPackageDir)" DestinationFile="$(ProjectDir)$(ZipFileName)" Overwrite="true" />
    <RemoveDir Directories="$(TempPackageDir)" />
    <Message Text="--- Mod successfully packaged at: $(ProjectDir)$(ZipFileName) ---" Importance="high" />
  </Target>

</Project>
