using System.Collections.Generic;

namespace TRLDynamicSpawnServer.Helpers
{
    public static class Localization
    {
        public static string CurrentLanguage { get; set; } = "en-US";

        public static readonly Dictionary<string, string> SupportedLanguages = new Dictionary<string, string>
        {
            { "en-US", "🇺🇸 English" },
            { "pt-BR", "🇧🇷 Português" },
            { "ru-RU", "🇷🇺 Русский" },
            { "es-ES", "🇪🇸 Español" },
            { "zh-CN", "🇨🇳 中文" }
        };

        private static readonly Dictionary<string, Dictionary<string, string>> Dictionaries = new Dictionary<string, Dictionary<string, string>>
        {
            {
                "pt-BR", new Dictionary<string, string>
                {
                    { "Tutorial / Home Page", "Tutorial / Página Inicial" },
                    { "Global Settings", "Configurações Globais" },
                    { "Events", "Eventos" },
                    { "Difficulty Roulette", "Roleta de Dificuldade" },
                    { "Custom Spawns (MOAR)", "Spawns Personalizados (MAIS)" },
                    { "Map Configs", "Configurações de Mapa" },
                    { "Boss Config", "Configuração de Chefes" },
                    { "Global Presets (Faction Ratio)", "Predefinições Globais (Proporção de Facções)" },
                    { "Preset (Faction Ratio)", "Predefinição (Proporção de Facções)" },
                    { "Globals", "Globais" },
                    { "Global Boss Controls", "Controles Globais de Chefes" },
                    { "Active Preset", "Predefinição Ativa" },
                    { "Balanced", "Equilibrado" },
                    { "PMC War", "Guerra de PMCs" },
                    { "Scav Infestation", "Infestação de Scavs" },
                    { "Quiet Raid", "Raid Tranquila" },
                    { "Warzone", "Zona de Guerra" },
                    { "Random", "Aleatório" },
                    { "50% PMCs / 50% Scavs. The classic SPT balance.", "50% PMCs / 50% Scavs. O clássico balanceamento do SPT." },
                    { "70% PMCs / 30% Scavs. Prepare to fight for every inch.", "70% PMCs / 30% Scavs. Prepare-se para lutar por cada centímetro." },
                    { "30% PMCs / 70% Scavs. A true horde of scavs on the map.", "30% PMCs / 70% Scavs. Uma verdadeira horda de scavs no mapa." },
                    { "Well-spaced spawn waves. Plenty of time to loot and explore without much pressure.", "Ondas bem espaçadas. Bastante tempo para lootear e explorar sem muita pressão." },
                    { "Extremely fast waves, short respawns, and extra chance of surprise Rogue/Raider invasions. Pure chaos.", "Ondas extremamente rápidas, respawns curtos e chance extra de invasões surpresa de Rogues/Raiders. Caos puro." },
                    { "Silently picks one of the 5 presets above at the start of each raid.", "Escolhe silenciosamente uma das 5 predefinições acima no início de cada raid." },
                    { "Note: Elites (Bosses, Raiders, etc) always spawn first. The preset applies to the remaining slots.", "Nota: Elites (Chefes, Raiders, etc) sempre nascem primeiro. A predefinição se aplica aos espaços restantes." },
                    { "Global Timers", "Temporizadores Globais" },
                    { "Delay Before First Wave (seconds)", "Atraso antes da primeira onda (segundos)" },
                    { "Seconds Between Waves (seconds)", "Segundos entre ondas (segundos)" },
                    { "Advanced Settings", "Configurações Avançadas" },
                    { "Enable Map Overlap Culling", "Ativar Otimização de Sobreposição de Mapas" },
                    { "Disable All Bosses", "Desativar Todos os Chefes" },
                    { "Enable Boss Open Zones", "Ativar Zonas Abertas de Chefes" },
                    { "Disable Flea Market Bots", "Desativar Bots do Mercado de Pulgas" },
                    { "Enable Scav Group Spawns", "Ativar Spawns de Grupos de Scavs" },
                    { "Current Map Profile", "Perfil do Mapa Atual" },
                    { "Active Event", "Evento Ativo" },
                    { "Max Bot Count", "Contagem Máxima de Bots" },
                    { "Time Between Spawns", "Tempo Entre Spawns" },
                    { "Distance Between Spawns", "Distância Entre Spawns" },
                    { "Time to wait before checking bounds", "Tempo de espera antes de verificar limites" },
                    { "Spawn Amount Multiplier", "Multiplicador de Quantidade de Spawns" },
                    { "Allow Ghost PMCs", "Permitir PMCs Fantasmas" },
                    { "Disable Boss Open Zones", "Desativar Zonas Abertas de Chefes" },
                    { "Spawn Config", "Configuração de Spawns" },
                    { "Spawn Amount Randomizer", "Randomizador de Quantidade de Spawns" },
                    { "Spawn Chance Mult (Difficulty)", "Multiplicador de Chance (Dificuldade)" },
                    { "Enable Progressive Difficulty", "Ativar Dificuldade Progressiva" },
                    { "Maximum Limit of Bots", "Limite Máximo de Bots" },
                    { "Despawn Timer (seconds)", "Tempo de Despawn (segundos)" },
                    { "Max Bots in Game", "Máximo de Bots no Jogo" },
                    { "Minimum Distance Between Players", "Distância Mínima Entre Jogadores" },
                    { "Use Dynamic Waves", "Usar Ondas Dinâmicas" },
                    { "Disable Custom Spawns", "Desativar Spawns Personalizados" },
                    { "Settings saved successfully", "Configurações salvas com sucesso" },
                    { "Error saving settings", "Erro ao salvar configurações" },
                    { "No event active", "Nenhum evento ativo" },
                    { "Random Event", "Evento Aleatório" },
                    { "Menu", "Menu" },
                    { "Select an item...", "Selecione um item..." },
                    { "Settings", "Configurações" },
                    { "Spawn Radius", "Raio de Spawn" },
                    { "Min (only spawn above min) - Distance from players to allow spawns:", "Mínimo (somente spawn acima de min) - Distância do jogador para permitir spawns:" },
                    { "Max (only spawn below max):", "Máximo (somente spawn abaixo de max):" },
                    { "Max Spawn/Despawn Limit Distance (m):", "Distância Limite de Spawn/Despawn Máxima (m):" },
                    { "Teleport Bots", "Teletransporte de Bots" },
                    { "Teleport bots?:", "Teleportar bots?:" },
                    { "Teleport Minimum Distance (m) - Safe distance from players for teleport target:", "Distância Mínima de Teletransporte (m) - Distância segura do jogador para o destino do teleporte:" },
                    { "Check Interval (seconds) - How often to scan bot distances:", "Intervalo de Verificação (segundos) - Frequência de checagem da distância do bot:" },
                    { "Include PMCs:", "Incluir PMCs:" },
                    { "Welcome to TRL Dynamic Spawn!", "Bem-vindo ao TRL Dynamic Spawn!" },
                    { "The evolution of spawn in SPTarkov: Combining the best of MOAR with the control of ABPS.", "A evolução do spawn no SPTarkov: Combinando o melhor do MOAR com o controle do ABPS." },
                    { "How does the Mod work?", "Como funciona o Mod?" },
                    { "TRL Dynamic Spawn is not just a simple bot manager. It completely rebuilds how the game decides when, where, and who will spawn in your raid.", "TRL Dynamic Spawn não é apenas um simples gerenciador de bots. Ele reconstrói completamente como o jogo decide quando, onde e quem nascerá na sua raid." },
                    { "Instead of letting SPTarkov dump all bots at once at the start of the match, the mod creates dynamic waves (Hordes), which evaluate the maximum amount of bots allowed on the map (BotCap) and fill the available slots periodically. This ensures always alive maps and constant combat, without destroying your PC performance.", "Em vez de deixar o SPTarkov despejar todos os bots de uma vez no início da partida, o mod cria ondas dinâmicas (Hordas), que avaliam a quantidade máxima de bots permitida no mapa (BotCap) e preenchem os espaços disponíveis periodicamente. Isso garante mapas sempre vivos e combate constante, sem destruir o desempenho do seu PC." },
                    { "The Union: MOAR + ABPS", "A União: MOAR + ABPS" },
                    { "This project was born from the idea of merging two great philosophies of spawn mods:", "Este projeto nasceu da ideia de fundir duas grandes filosofias de mods de spawn:" },
                    { "The Logic of MOAR:", "A Lógica do MOAR:" },
                    { "Inherits the concept of continuous waves and the Custom Spawns system. The mod decides the faction distribution and keeps sending reinforcements as bots die.", "Herda o conceito de ondas contínuas e o sistema de Spawns Personalizados. O mod decide a distribuição de facções e continua enviando reforços conforme os bots morrem." },
                    { "The Control of ABPS (Advanced Bot Placement System):", "O Controle do ABPS (Advanced Bot Placement System):" },
                    { "TRLDynamicSpawn brings the incredible interface and absurd level of control over Bosses and Elites. You can configure spawn chances and, most importantly, in exactly which specific zones each Boss is allowed to appear on each map.", "TRLDynamicSpawn traz a interface incrível e o nível absurdo de controle sobre Chefes e Elites. Você pode configurar chances de spawn e, mais importante, em quais zonas específicas cada Chefe tem permissão para aparecer em cada mapa." },
                    { "Horde System & Limits (BotCap)", "Sistema de Horda e Limites (BotCap)" },
                    { "The mod uses the horde spawn system (Spawn Wave). Here is how it works:", "O mod utiliza o sistema de spawn em horda (Spawn Wave). Funciona assim:" },
                    { "Timers:", "Temporizadores:" },
                    { "You configure in the Map Configs page the time for the first wave (Delay Before First Wave) and the interval between subsequent waves (Seconds Between Waves).", "Você configura na página de Configurações de Mapa o tempo para a primeira onda (Atraso antes da primeira onda) e o intervalo entre as ondas subsequentes (Segundos entre ondas)." },
                    { "Smart Filling:", "Preenchimento Inteligente:" },
                    { "At each cycle, the mod checks how many bots are alive. If the map supports 20 bots and only has 10 alive, the next wave will try to generate 10 new bots to fill the map again.", "A cada ciclo, o mod verifica quantos bots estão vivos. Se o mapa suporta 20 bots e possui apenas 10 vivos, a próxima onda tentará gerar 10 novos bots para preencher o mapa novamente." },
                    { "Elite Priority:", "Prioridade de Elites:" },
                    { "Bosses, Rogues, Raiders, and Cultists always spawn first, as soon as the map loads. If Reshala has a 100% chance to spawn at Dorms, he and his guards will reserve their spots in the BotCap immediately.", "Chefes, Rogues, Raiders e Cultistas sempre nascem primeiro, assim que o mapa carrega. Se Reshala tiver 100% de chance de nascer no Dormitório, ele e seus guardas reservarão suas vagas no BotCap imediatamente." },
                    { "Configuration Guide (Sidebar Menu)", "Guia de Configuração (Menu Lateral)" },
                    { "Use the menu on the left to customize every aspect of your raid:", "Use o menu à esquerda para personalizar cada aspecto da sua raid:" },
                    { "Map Configs:", "Configurações de Mapa:" },
                    { "Configure general map settings, preset faction ratios, horde wave timers, and anti-overlap distances.", "Configure definições gerais de mapas, proporção de facções por predefinição, temporizadores de ondas e distâncias de anti-sobreposição." },
                    { "Difficulty Roulette:", "Roleta de Dificuldade:" },
                    { "Set the difficulty weights. Do you want 50% of PMCs to be Hard and 50% Impossible? Configure the weights here.", "Defina os pesos de dificuldade. Quer que 50% dos PMCs sejam Difíceis e 50% Impossíveis? Configure os pesos aqui." },
                    { "Custom Spawns (MOAR):", "Spawns Personalizados (MAIS):" },
                    { "Injects a list of new custom spawn points into the map. Adds new possibilities for PMCs, Scavs, Snipers, and Player spawns.", "Injeta uma lista de novos pontos de spawn personalizados no mapa. Adiciona novas possibilidades para PMCs, Scavs, Snipers e spawns de Jogador." },
                    { "Bot Config:", "Configuração de Chefes:" },
                    { "Click on a Boss name and change their spawn chance (%) and exactly the zones they are allowed to spawn in.", "Clique no nome de um Chefe e altere sua chance de spawn (%) e exatamente as zonas em que eles têm permissão para nascer." },
                    { "Enabled", "Ativado" },
                    { "Disabled", "Desativado" },
                    { "SETTINGS", "CONFIGURAÇÕES" },
                    { "Undo", "Desfazer" },
                    { "Default", "Padrão" },
                    { "Reload Config", "Recarregar Config" },
                    { "Save Config", "Salvar Config" },
                    { "Changes:", "Alterações:" },
                    { "Cancel", "Cancelar" }
                }
            },
            {
                "ru-RU", new Dictionary<string, string>
                {
                    { "Tutorial / Home Page", "Учебник / Главная" },
                    { "Global Settings", "Глобальные настройки" },
                    { "Events", "События" },
                    { "Difficulty Roulette", "Рулетка сложности" },
                    { "Custom Spawns (MOAR)", "Пользовательские спауны" },
                    { "Map Configs", "Настройки карты" },
                    { "Boss Config", "Настройки боссов" },
                    { "Global Presets (Faction Ratio)", "Глобальные пресеты (соотношение фракций)" },
                    { "Active Preset", "Активный пресет" },
                    { "50% PMCs / 50% Scavs. The classic SPT balance.", "50% ЧВК / 50% Дикие. Классический баланс SPT." },
                    { "Note: Elites (Bosses, Raiders, etc) always spawn first. The preset applies to the remaining slots.", "Примечание: Элита всегда появляется первой." },
                    { "Global Timers", "Глобальные таймеры" },
                    { "Delay Before First Wave (seconds)", "Задержка перед первой волной (сек)" },
                    { "Seconds Between Waves (seconds)", "Секунды между волнами (сек)" },
                    { "Advanced Settings", "Дополнительные настройки" },
                    { "Enable Map Overlap Culling", "Включить отбраковку наложения карт" },
                    { "Disable All Bosses", "Отключить всех боссов" },
                    { "Enable Boss Open Zones", "Включить открытые зоны боссов" },
                    { "Disable Flea Market Bots", "Отключить ботов барахолки" },
                    { "Enable Scav Group Spawns", "Включить группы диких" },
                    { "Current Map Profile", "Текущий профиль карты" },
                    { "Active Event", "Активное событие" },
                    { "Max Bot Count", "Макс. количество ботов" },
                    { "Time Between Spawns", "Время между спаунами" },
                    { "Distance Between Spawns", "Дистанция между спаунами" },
                    { "Time to wait before checking bounds", "Время ожидания перед проверкой границ" },
                    { "Spawn Amount Multiplier", "Множитель количества" },
                    { "Allow Ghost PMCs", "Разрешить призрачных ЧВК" },
                    { "Disable Boss Open Zones", "Отключить открытые зоны боссов" },
                    { "Spawn Config", "Настройки спауна" },
                    { "Spawn Amount Randomizer", "Рандомизатор количества" },
                    { "Spawn Chance Mult (Difficulty)", "Множитель шанса (Сложность)" },
                    { "Enable Progressive Difficulty", "Прогрессивная сложность" },
                    { "Maximum Limit of Bots", "Максимальный лимит ботов" },
                    { "Despawn Timer (seconds)", "Таймер исчезновения (сек)" },
                    { "Max Bots in Game", "Макс. ботов в игре" },
                    { "Minimum Distance Between Players", "Мин. дистанция между игроками" },
                    { "Use Dynamic Waves", "Динамические волны" },
                    { "Disable Custom Spawns", "Отключить пользовательские спауны" },
                    { "Settings saved successfully", "Настройки успешно сохранены" },
                    { "Error saving settings", "Ошибка при сохранении" },
                    { "No event active", "Нет активного события" },
                    { "Random Event", "Случайное событие" },
                    { "Menu", "Меню" },
                    { "Select an item...", "Выберите элемент..." },
                    { "Settings", "Настройки" }
                }
            },
            {
                "es-ES", new Dictionary<string, string>
                {
                    { "Tutorial / Home Page", "Tutorial / Inicio" },
                    { "Global Settings", "Configuraciones Globales" },
                    { "Events", "Eventos" },
                    { "Difficulty Roulette", "Ruleta de Dificultad" },
                    { "Custom Spawns (MOAR)", "Spawns Personalizados" },
                    { "Map Configs", "Configuración de Mapa" },
                    { "Boss Config", "Configuración de Jefes" },
                    { "Global Presets (Faction Ratio)", "Ajustes Globales (Proporción de Facción)" },
                    { "Active Preset", "Ajuste Activo" },
                    { "50% PMCs / 50% Scavs. The classic SPT balance.", "50% PMCs / 50% Scavs. Balance clásico." },
                    { "Note: Elites (Bosses, Raiders, etc) always spawn first. The preset applies to the remaining slots.", "Nota: Élite (Jefes, Raiders, etc) siempre aparecen primero." },
                    { "Global Timers", "Temporizadores Globales" },
                    { "Delay Before First Wave (seconds)", "Retraso antes de la primera ola (seg)" },
                    { "Seconds Between Waves (seconds)", "Segundos entre olas (seg)" },
                    { "Advanced Settings", "Configuraciones Avanzadas" },
                    { "Enable Map Overlap Culling", "Activar optimización de superposición" },
                    { "Disable All Bosses", "Desactivar todos los jefes" },
                    { "Enable Boss Open Zones", "Activar zonas abiertas de jefes" },
                    { "Disable Flea Market Bots", "Desactivar bots del mercado" },
                    { "Enable Scav Group Spawns", "Activar grupos de scavs" },
                    { "Current Map Profile", "Perfil de Mapa Actual" },
                    { "Active Event", "Evento Activo" },
                    { "Max Bot Count", "Conteo Máx. de Bots" },
                    { "Time Between Spawns", "Tiempo entre Spawns" },
                    { "Distance Between Spawns", "Distancia entre Spawns" },
                    { "Time to wait before checking bounds", "Tiempo antes de verificar límites" },
                    { "Spawn Amount Multiplier", "Multiplicador de cantidad de spawn" },
                    { "Allow Ghost PMCs", "Permitir PMCs Fantasmas" },
                    { "Disable Boss Open Zones", "Desactivar zonas abiertas de jefes" },
                    { "Spawn Config", "Configuración de Spawn" },
                    { "Spawn Amount Randomizer", "Aleatorizador de cantidad" },
                    { "Spawn Chance Mult (Difficulty)", "Multiplicador de probabilidad (Dificultad)" },
                    { "Enable Progressive Difficulty", "Dificultad progresiva" },
                    { "Maximum Limit of Bots", "Límite máximo de bots" },
                    { "Despawn Timer (seconds)", "Tiempo de desaparición (seg)" },
                    { "Max Bots in Game", "Máx. de bots en juego" },
                    { "Minimum Distance Between Players", "Distancia mínima entre jugadores" },
                    { "Use Dynamic Waves", "Usar Olas Dinámicas" },
                    { "Disable Custom Spawns", "Desactivar Spawns Personalizados" },
                    { "Settings saved successfully", "Configuraciones guardadas" },
                    { "Error saving settings", "Error guardando" },
                    { "No event active", "Sin evento activo" },
                    { "Random Event", "Evento Aleatorio" },
                    { "Menu", "Menú" },
                    { "Select an item...", "Selecciona un elemento..." },
                    { "Settings", "Ajustes" }
                }
            },
            {
                "zh-CN", new Dictionary<string, string>
                {
                    { "Tutorial / Home Page", "教程 / 主页" },
                    { "Global Settings", "全局设置" },
                    { "Events", "事件" },
                    { "Difficulty Roulette", "难度轮盘" },
                    { "Custom Spawns (MOAR)", "自定义生成" },
                    { "Map Configs", "地图配置" },
                    { "Boss Config", "首领配置" },
                    { "Global Presets (Faction Ratio)", "全局预设 (派系比例)" },
                    { "Active Preset", "当前预设" },
                    { "50% PMCs / 50% Scavs. The classic SPT balance.", "50% PMC / 50% Scav。 经典的SPT平衡。" },
                    { "Note: Elites (Bosses, Raiders, etc) always spawn first. The preset applies to the remaining slots.", "注意：精英（Boss，Raider等）总是首先生成。" },
                    { "Global Timers", "全局计时器" },
                    { "Delay Before First Wave (seconds)", "第一波前延迟（秒）" },
                    { "Seconds Between Waves (seconds)", "波之间秒数（秒）" },
                    { "Advanced Settings", "高级设置" },
                    { "Enable Map Overlap Culling", "启用地图重叠剔除" },
                    { "Disable All Bosses", "禁用所有Boss" },
                    { "Enable Boss Open Zones", "启用Boss开放区" },
                    { "Disable Flea Market Bots", "禁用跳蚤市场机器人" },
                    { "Enable Scav Group Spawns", "启用Scav小队生成" },
                    { "Current Map Profile", "当前地图配置" },
                    { "Active Event", "当前事件" },
                    { "Max Bot Count", "最大机器人数量" },
                    { "Time Between Spawns", "生成间隔时间" },
                    { "Distance Between Spawns", "生成间隔距离" },
                    { "Time to wait before checking bounds", "检查边界前等待时间" },
                    { "Spawn Amount Multiplier", "生成数量倍数" },
                    { "Allow Ghost PMCs", "允许幽灵PMC" },
                    { "Disable Boss Open Zones", "禁用Boss开放区" },
                    { "Spawn Config", "生成配置" },
                    { "Spawn Amount Randomizer", "生成数量随机数" },
                    { "Spawn Chance Mult (Difficulty)", "生成几率倍数（难度）" },
                    { "Enable Progressive Difficulty", "启用渐进难度" },
                    { "Maximum Limit of Bots", "机器人最大限制" },
                    { "Despawn Timer (seconds)", "消失计时器（秒）" },
                    { "Max Bots in Game", "游戏内最大机器人数量" },
                    { "Minimum Distance Between Players", "玩家间最小距离" },
                    { "Use Dynamic Waves", "使用动态波次" },
                    { "Disable Custom Spawns", "禁用自定义生成" },
                    { "Settings saved successfully", "设置已成功保存" },
                    { "Error saving settings", "保存设置时出错" },
                    { "No event active", "没有活动事件" },
                    { "Random Event", "随机事件" },
                    { "Menu", "菜单" },
                    { "Select an item...", "选择一项..." },
                    { "Settings", "设置" }
                }
            }
        };

        public static string T(string englishText)
        {
            if (CurrentLanguage == "en-US") return englishText;

            if (Dictionaries.TryGetValue(CurrentLanguage, out var dict))
            {
                if (dict.TryGetValue(englishText, out var translated))
                {
                    return translated;
                }
            }

            return englishText;
        }
    }
}
