<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SkillDistribution</RootNamespace>
    <Title>Skill Distribution</Title>
    <Authors>ZGFueDkx</Authors>
    <AssemblyName>SkillDistribution-Server</AssemblyName>
    <AssemblyVersion>1.2.2</AssemblyVersion>
    <Version>$(AssemblyVersion)</Version>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Copyright>Copyright © 2025 $(Authors)</Copyright>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.0" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.0" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.0" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="set &quot;dest=$(ProjectDir)..\..\..\SPT\user\mods\$(RootNamespace)&quot;&#xD;&#xA;mkdir %25dest%25&#xD;&#xA;copy &quot;$(TargetPath)&quot; &quot;%25dest%25\$(TargetFileName)&quot;&#xD;&#xA;robocopy &quot;$(ProjectDir)\config&quot; &quot;%25dest%25\config&quot; /e" />
  </Target>

</Project>
