<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>Manimal.LoadAmmoAnim.Fika</RootNamespace>
    <AssemblyName>LoadAmmoAnimClientFika</AssemblyName>
    <Nullable>disable</Nullable>
    <Authors>Manimal</Authors>
    <AssemblyVersion>$(ModVersion).0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Configurations>Debug;Release</Configurations>
    <Version>$(ModVersion)</Version>
    <LangVersion>latest</LangVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoadAmmoAnimClient\LoadAmmoAnimClient.csproj" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Fika.Core">
      <HintPath>$(SPTPath)\BepInEx\plugins\Fika\Fika.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(SPTPath)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="spt-common">
      <HintPath>$(SPTPath)\BepInEx\plugins\spt\spt-common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>$(SPTPath)\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(SPTPath)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Comfort.Unity">
      <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Comfort.Unity.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ItemComponent.Types">
      <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\ItemComponent.Types.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ItemTemplate.Types">
      <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\ItemTemplate.Types.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
