public enum EItemType
{
	[GAttribute24("None")]
	None,
	[GAttribute24("Ammo")]
	Ammo,
	[GAttribute24("Barter")]
	Barter,
	[GAttribute24("Container")]
	Container,
	[GAttribute24("Food")]
	Food,
	[GAttribute24("Backpack")]
	Backpack,
	[GAttribute24("Goggles")]
	Goggles,
	[GAttribute24("Rig")]
	Rig,
	[GAttribute24("Armor")]
	Armor,
	[GAttribute24("Equipment")]
	Equipment,
	[GAttribute24("Grenade")]
	Grenade,
	[GAttribute24("Info")]
	Info,
	[GAttribute24("Keys")]
	Keys,
	[GAttribute24("Knife")]
	Knife,
	[GAttribute24("Magazine")]
	Magazine,
	[GAttribute24("Meds")]
	Meds,
	[GAttribute24("Mod")]
	Mod,
	[GAttribute24("Special")]
	Special,
	[GAttribute24("Weapon")]
	Weapon,
	[GAttribute24("All")]
	All
}
