namespace EFT;

public enum ESkillId : byte
{
	[GAttribute24("Endurance")]
	Endurance,
	[GAttribute24("Strength")]
	Strength,
	[GAttribute24("Vitality")]
	Vitality,
	[GAttribute24("Health")]
	Health,
	[GAttribute24("StressResistance")]
	StressResistance,
	[GAttribute24("Metabolism")]
	Metabolism,
	[GAttribute24("Immunity")]
	Immunity,
	[GAttribute24("Perception")]
	Perception,
	[GAttribute24("Intellect")]
	Intellect,
	[GAttribute24("Attention")]
	Attention,
	[GAttribute24("Charisma")]
	Charisma,
	[GAttribute24("Memory")]
	Memory,
	[GAttribute24("MagDrills")]
	MagDrills,
	[GAttribute24("Pistol")]
	Pistol,
	[GAttribute24("Revolver")]
	Revolver,
	[GAttribute24("SMG")]
	SMG,
	[GAttribute24("Assault")]
	Assault,
	[GAttribute24("Shotgun")]
	Shotgun,
	[GAttribute24("Sniper")]
	Sniper,
	[GAttribute24("LMG")]
	LMG,
	[GAttribute24("HMG")]
	HMG,
	[GAttribute24("Launcher")]
	Launcher,
	[GAttribute24("AttachedLauncher")]
	AttachedLauncher,
	[GAttribute24("Throwing")]
	Throwing,
	[GAttribute24("Misc")]
	Misc,
	[GAttribute24("Melee")]
	Melee,
	[GAttribute24("DMR")]
	DMR,
	[GAttribute24("DrawMaster")]
	DrawMaster,
	[GAttribute24("AimMaster")]
	AimMaster,
	[GAttribute24("RecoilControl")]
	RecoilControl,
	[GAttribute24("TroubleShooting")]
	TroubleShooting,
	[GAttribute24("Sniping")]
	Sniping,
	[GAttribute24("CovertMovement")]
	CovertMovement,
	[GAttribute24("ProneMovement")]
	ProneMovement,
	[GAttribute24("FirstAid")]
	FirstAid,
	[GAttribute24("FieldMedicine")]
	FieldMedicine,
	[GAttribute24("Surgery")]
	Surgery,
	[GAttribute24("LightVests")]
	LightVests,
	[GAttribute24("HeavyVests")]
	HeavyVests,
	[GAttribute24("WeaponModding")]
	WeaponModding,
	[GAttribute24("AdvancedModding")]
	AdvancedModding,
	[GAttribute24("NightOps")]
	NightOps,
	[GAttribute24("SilentOps")]
	SilentOps,
	[GAttribute24("Lockpicking")]
	Lockpicking,
	[GAttribute24("Search")]
	Search,
	[GAttribute24("WeaponTreatment")]
	WeaponTreatment,
	[GAttribute24("Freetrading")]
	Freetrading,
	[GAttribute24("Auctions")]
	Auctions,
	[GAttribute24("Cleanoperations")]
	Cleanoperations,
	[GAttribute24("Barter")]
	Barter,
	[GAttribute24("Shadowconnections")]
	Shadowconnections,
	[GAttribute24("Taskperformance")]
	Taskperformance,
	[GAttribute24("BearAssaultoperations")]
	BearAssaultoperations,
	[GAttribute24("BearAuthority")]
	BearAuthority,
	[GAttribute24("BearAksystems")]
	BearAksystems,
	[GAttribute24("BearHeavycaliber")]
	BearHeavycaliber,
	[GAttribute24("BearRawpower")]
	BearRawpower,
	[GAttribute24("UsecArsystems")]
	UsecArsystems,
	[GAttribute24("UsecDeepweaponmodding")]
	UsecDeepweaponmodding,
	[GAttribute24("UsecLongrangeoptics")]
	UsecLongrangeoptics,
	[GAttribute24("UsecNegotiations")]
	UsecNegotiations,
	[GAttribute24("UsecTactics")]
	UsecTactics,
	[GAttribute24("BotReload")]
	BotReload,
	[GAttribute24("BotSound")]
	BotSound,
	[GAttribute24("AimDrills")]
	AimDrills,
	[GAttribute24("HideoutManagement")]
	HideoutManagement,
	[GAttribute24("Crafting")]
	Crafting
}
