<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>MOARServer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <Version>3.1.6</Version>
    <!-- The two lines below will set the output path for the binaries -->
    <OutputPath>bin\$(Configuration)\$(ProjectName)\$(AssemblyName)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.3" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.3" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.0.3" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.3" />
    <PackageReference Include="SPTarkov.Server.Web" Version="4.0.3" />
  </ItemGroup>
    
  <ItemGroup>
    <None Update="LICENSE.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Update="config\**\*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>


    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>None</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    </PropertyGroup>

</Project>
