<Project>

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>disable</Nullable>
    <Authors>7Bpencil</Authors>
    <Copyright>Copyright (c) 7Bpencil 2026</Copyright>
    <AssemblyVersion>1.17.1</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Version>$(AssemblyVersion)</Version>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <SPTPath>..\..\..\..</SPTPath>
    <OutPath>$(SPTPath)\BepInEx\plugins\7Bpencil.WeaponCamoAndStickers</OutPath>
    <StagePath>$(ProjectDir)..\..\Stage\BepInEx\plugins\7Bpencil.WeaponCamoAndStickers</StagePath>
    <AssemblySearchPaths>
      $(AssemblySearchPaths);
      $(SPTPath)\EscapeFromTarkov_Data\Managed;
      $(SPTPath)\BepInEx\core;
      $(SPTPath)\BepInEx\plugins\spt;
      $(SPTPath)\BepInEx\plugins\Fika;
    </AssemblySearchPaths>
  </PropertyGroup>

  <Target Name="CopyToSPT" AfterTargets="AfterBuild">
    <Exec Command="mkdir &quot;$(OutPath)&quot;" ContinueOnError="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(OutPath)" />
  </Target>

  <Target Name="CopyToStage" AfterTargets="AfterBuild" Condition="'$(Configuration)'=='Release'">
    <Exec Command="mkdir &quot;$(StagePath)&quot;" ContinueOnError="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(StagePath)" />
  </Target>

</Project>
