# File: AutoSync-Cache.ps1
# 3D bundle cache manager + SPT server watcher (production).
#
# What it does, in order:
#   1. Scans server mods for bundle assets (user\mods\<mod>\bundles.json + bundles\*.bundle).
#      Only mods with bundles matter here - logic/JSON-only mods never require opening the game.
#   2. Invalidates stale cache copies (changed bundles) and deletes orphans (removed mods)
#      directly, WITHOUT opening the game.
#   3. Opens server + Fika headless client ONLY if some bundle has no valid copy in
#      user\cache\bundles (the client is what populates that cache on download).
#   4. Mirrors user\cache into Launcher-Updater\mods_repo so the launcher manifest
#      distributes the pre-built cache to players.
#   5. Starts the SPT server in watcher mode (auto-restart).
#
# Notes:
#   - bundleHashCache.json (in user\cache) is regenerated by the SERVER on boot; the game
#     client is irrelevant for it. Only user\cache\bundles needs a client run.
#   - State file: autosync-state.json (replaces the legacy ultimo_mod_hash.txt).
#   - The launcher (2.0.0) does NOT read any of these files; it only consumes the manifest
#     generated by ModUpdater from mods_repo (MD5 per file).
#
# Usage:
#   AutoSync-Cache.ps1                 normal production run
#   AutoSync-Cache.ps1 -CheckOnly      report what would happen, change nothing, skip watcher
#   AutoSync-Cache.ps1 -Root <path>    override the root folder (testing on another install)

param(
    [string]$Root,
    [switch]$CheckOnly
)

if (-not $Root) {
    $Root = Split-Path -Parent $MyInvocation.MyCommand.Definition
}
Set-Location $Root

$Host.UI.RawUI.WindowTitle = "Sincronizador de Cache e SPT Server Watcher"

# --- PATHS ---
$ServerPath = Join-Path $Root "SPT"
$ServerExePath = Join-Path $ServerPath "SPT.Server.exe"
$ServerCachePath = Join-Path $ServerPath "user\cache"
$CacheBundlesPath = Join-Path $ServerCachePath "bundles"
$ModsPath = Join-Path $ServerPath "user\mods"

$HeadlessExePath = Join-Path $Root "FikaHeadlessManager.exe"
$BepinexLogPath = Join-Path $Root "BepInEx\LogOutput.log"
$UpdaterCachePath = Join-Path $Root "Launcher-Updater\mods_repo\SPT\user\cache"

$StateFilePath = Join-Path $Root "autosync-state.json"
$LegacyHashFilePath = Join-Path $Root "ultimo_mod_hash.txt"

# --- TUNING ---
$ServerStartTimeoutSec = 420   # max wait for the server to come online during warmup
$ClientLoadTimeoutSec = 900    # max wait for the headless client to connect (downloads bundles)
$MaxListedItems = 20           # max items printed per report list
# --------------------------------

Write-Host "--- GERENCIADOR DE CACHE 3D E SERVIDOR SPT ---" -ForegroundColor Cyan
Write-Host "Local: $Root"
if ($CheckOnly) { Write-Host "MODO CHECK-ONLY: nenhuma alteracao sera feita." -ForegroundColor Yellow }
Write-Host "----------------------------------------------"

if (!(Test-Path $ServerExePath)) {
    Write-Host "ERRO CRITICO: Arquivo '$ServerExePath' nao foi encontrado!" -ForegroundColor Red
    Read-Host "Pressione ENTER para sair..."
    exit 1
}

# =====================================================================
# Functions
# =====================================================================

# Snapshot of everything that can affect the 3D cache: for each mod that ships bundles
# (has bundles.json), record bundles.json itself plus every .bundle file.
# Key: "<mod>/bundles/<relpath>" (forward slashes). Value: "<size>|<mtimeUtcTicks>".
function Get-SourceBundleState {
    param([string]$modsPath)
    $state = @{}
    if (-not (Test-Path $modsPath)) { return $state }

    foreach ($mod in Get-ChildItem -Path $modsPath -Directory -ErrorAction SilentlyContinue) {
        $manifestPath = Join-Path $mod.FullName "bundles.json"
        if (-not (Test-Path $manifestPath)) { continue }

        $manifest = Get-Item -LiteralPath $manifestPath
        $state["$($mod.Name)/bundles.json"] = "$($manifest.Length)|$($manifest.LastWriteTimeUtc.Ticks)"

        $bundlesDir = Join-Path $mod.FullName "bundles"
        if (Test-Path $bundlesDir) {
            foreach ($f in Get-ChildItem -Path $bundlesDir -Recurse -File -Filter "*.bundle" -ErrorAction SilentlyContinue) {
                $rel = $f.FullName.Substring($mod.FullName.Length + 1).Replace('\', '/')
                $state["$($mod.Name)/$rel"] = "$($f.Length)|$($f.LastWriteTimeUtc.Ticks)"
            }
        }
    }
    return $state
}

# Maps each source bundle to its expected copy inside user\cache\bundles.
# The client cache mirrors the relpath under <mod>\bundles\ 1:1.
# Returns: hashtable cacheRelPath -> source full path.
function Get-ExpectedCacheMap {
    param([hashtable]$sourceState, [string]$modsPath)
    $map = @{}
    foreach ($key in $sourceState.Keys) {
        $idx = $key.IndexOf("/bundles/")
        if ($idx -lt 0) { continue }  # skips the bundles.json entries
        $cacheRel = $key.Substring($idx + 9)
        $map[$cacheRel] = Join-Path $modsPath ($key.Replace('/', '\'))
    }
    return $map
}

# Bundles whose cache copy is missing or has a different size (needs the game to populate).
function Get-CacheGaps {
    param([hashtable]$expectedMap, [string]$cacheBundles)
    $gaps = @()
    foreach ($rel in $expectedMap.Keys) {
        $src = Get-Item -LiteralPath $expectedMap[$rel] -ErrorAction SilentlyContinue
        if ($null -eq $src) { continue }
        $dst = Get-Item -LiteralPath (Join-Path $cacheBundles ($rel.Replace('/', '\'))) -ErrorAction SilentlyContinue
        if ($null -eq $dst -or $dst.Length -ne $src.Length) { $gaps += $rel }
    }
    # Plain return: every caller wraps with @(...), which restores the array correctly
    return $gaps
}

# Cache copies that no longer have a source bundle in any mod (mod removed/renamed).
function Get-OrphanCacheFiles {
    param([hashtable]$expectedMap, [string]$cacheBundles)
    $orphans = @()
    if (-not (Test-Path $cacheBundles)) { return $orphans }
    foreach ($f in Get-ChildItem -Path $cacheBundles -Recurse -File -Filter "*.bundle" -ErrorAction SilentlyContinue) {
        $rel = $f.FullName.Substring($cacheBundles.Length + 1).Replace('\', '/')
        if (-not $expectedMap.ContainsKey($rel)) { $orphans += $f }
    }
    # Plain return: every caller wraps with @(...), which restores the array correctly
    return $orphans
}

function Compare-BundleState {
    param([hashtable]$saved, [hashtable]$current)
    $added = @(); $changed = @(); $removed = @()
    foreach ($k in $current.Keys) {
        if (-not $saved.ContainsKey($k)) { $added += $k }
        elseif ($saved[$k] -ne $current[$k]) { $changed += $k }
    }
    foreach ($k in $saved.Keys) {
        if (-not $current.ContainsKey($k)) { $removed += $k }
    }
    return @{ Added = $added; Changed = $changed; Removed = $removed }
}

function Write-ItemList {
    param([string]$title, [array]$items, [string]$color = "Gray")
    if ($items.Count -eq 0) { return }
    Write-Host "  ${title}: $($items.Count)" -ForegroundColor $color
    foreach ($i in ($items | Select-Object -First $MaxListedItems)) {
        Write-Host "    - $i" -ForegroundColor DarkGray
    }
    if ($items.Count -gt $MaxListedItems) {
        Write-Host "    ... e mais $($items.Count - $MaxListedItems)" -ForegroundColor DarkGray
    }
}

function Save-State {
    param([hashtable]$bundles, [array]$knownMissing)
    $payload = @{
        version      = 2
        updatedAt    = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
        bundles      = $bundles
        knownMissing = @($knownMissing)
    }
    $payload | ConvertTo-Json -Depth 4 | Set-Content -Path $StateFilePath -Encoding UTF8
    if (Test-Path $LegacyHashFilePath) {
        Remove-Item -Path $LegacyHashFilePath -Force -ErrorAction SilentlyContinue
    }
}

# Opens server + headless client so the client downloads new bundles into user\cache\bundles,
# then shuts everything down. Returns $true on success, $false on any failure/timeout
# (on failure the state file is NOT updated, so the next run retries).
function Invoke-GameCacheWarmup {
    Write-Host "`n[1/4] Iniciando Servidor para carregamento de bundles..." -ForegroundColor Cyan
    $serverProcess = Start-Process -FilePath $ServerExePath -WorkingDirectory $ServerPath -PassThru

    Write-Host "Aguardando o Servidor ficar Online (timeout: ${ServerStartTimeoutSec}s)..." -ForegroundColor Yellow
    $serverLogsPath = Join-Path $ServerPath "user\logs\spt"
    $serverOnline = $false
    $sw = [System.Diagnostics.Stopwatch]::StartNew()

    Start-Sleep -Seconds 2
    while (-not $serverOnline) {
        if ($serverProcess.HasExited) {
            Write-Host "FALHA: o Servidor terminou inesperadamente durante o warmup." -ForegroundColor Red
            return $false
        }
        if ($sw.Elapsed.TotalSeconds -gt $ServerStartTimeoutSec) {
            Write-Host "FALHA: timeout aguardando o Servidor ficar online." -ForegroundColor Red
            $serverProcess | Stop-Process -Force -ErrorAction SilentlyContinue
            return $false
        }
        if (Test-Path $serverLogsPath) {
            $latestLog = Get-ChildItem -Path $serverLogsPath -Filter "spt*" -File -ErrorAction SilentlyContinue |
                Sort-Object LastWriteTime -Descending | Select-Object -First 1
            if ($latestLog) {
                $content = Get-Content -Path $latestLog.FullName -Tail 10 -ErrorAction SilentlyContinue
                if ($content -match "iniciou. Bom jogo" -or $content -match "Happy playing" -or $content -match "Started web server") {
                    $serverOnline = $true
                }
            }
        }
        Start-Sleep -Seconds 1
    }
    Write-Host "Servidor Online! Avancando..." -ForegroundColor Green

    Write-Host "`n[2/4] Iniciando FikaHeadlessManager para abrir o cliente..." -ForegroundColor Cyan
    if (-not (Test-Path $HeadlessExePath)) {
        Write-Host "FALHA: FikaHeadlessManager.exe nao encontrado em '$HeadlessExePath'." -ForegroundColor Red
        $serverProcess | Stop-Process -Force -ErrorAction SilentlyContinue
        return $false
    }

    # Delete the old log so a previous run's marker can't produce a false positive
    if (Test-Path $BepinexLogPath) {
        Remove-Item -Path $BepinexLogPath -Force -ErrorAction SilentlyContinue
    }
    $headlessProcess = Start-Process -FilePath $HeadlessExePath -WorkingDirectory $Root -PassThru

    Write-Host "`n>>> O JOGO ESTA ABRINDO... <<<" -ForegroundColor Yellow
    Write-Host "Aguardando 'Connected to HeadlessWebSocket' (timeout: ${ClientLoadTimeoutSec}s)..."

    $clientLoaded = $false
    $sw.Restart()
    while (-not $clientLoaded) {
        if ($headlessProcess.HasExited) {
            Write-Host "FALHA: o FikaHeadlessManager terminou antes do cliente carregar." -ForegroundColor Red
            break
        }
        if ($sw.Elapsed.TotalSeconds -gt $ClientLoadTimeoutSec) {
            Write-Host "FALHA: timeout aguardando o cliente carregar." -ForegroundColor Red
            break
        }
        if (Test-Path $BepinexLogPath) {
            $content = Get-Content -Path $BepinexLogPath -Tail 10 -ErrorAction SilentlyContinue
            if ($content -match "Connected to HeadlessWebSocket") {
                $clientLoaded = $true
            }
        }
        Start-Sleep -Seconds 1
    }

    if ($clientLoaded) {
        Write-Host "Cliente carregado com sucesso!" -ForegroundColor Green
    }

    Write-Host "`n[3/4] Fechando FikaHeadlessManager e o Jogo..." -ForegroundColor Cyan
    Get-Process -Name "EscapeFromTarkov" -ErrorAction SilentlyContinue | Stop-Process -Force
    if ($null -ne $headlessProcess -and -not $headlessProcess.HasExited) {
        $headlessProcess | Stop-Process -Force
    }

    Write-Host "[4/4] Fechando Servidor para liberar os arquivos de cache..." -ForegroundColor Cyan
    if (-not $serverProcess.HasExited) {
        $serverProcess | Stop-Process -Force
    }

    # Let processes release file handles before the robocopy step
    Start-Sleep -Seconds 3
    return $clientLoaded
}

# =====================================================================
# 1. Detect bundle changes (only bundles matter for the 3D cache)
# =====================================================================

Write-Host "Analisando bundles dos mods..." -ForegroundColor Yellow

$savedBundles = @{}
$knownMissing = @()
if (Test-Path $StateFilePath) {
    try {
        $stateJson = Get-Content -Path $StateFilePath -Raw | ConvertFrom-Json
        foreach ($p in $stateJson.bundles.PSObject.Properties) { $savedBundles[$p.Name] = [string]$p.Value }
        $knownMissing = @($stateJson.knownMissing | Where-Object { $_ })
    }
    catch {
        Write-Host "AVISO: estado anterior ilegivel ('$StateFilePath'); tratando como primeira execucao." -ForegroundColor Yellow
        $savedBundles = @{}
        $knownMissing = @()
    }
}
$isFirstRun = ($savedBundles.Count -eq 0)

$currentBundles = Get-SourceBundleState $ModsPath
$diff = Compare-BundleState $savedBundles $currentBundles
$expectedCache = Get-ExpectedCacheMap $currentBundles $ModsPath

$modsWithBundles = @($currentBundles.Keys | ForEach-Object { ($_ -split '/')[0] } | Sort-Object -Unique)
Write-Host "Mods com bundles: $($modsWithBundles.Count) | Bundles de origem: $($expectedCache.Count)" -ForegroundColor Gray

if ($isFirstRun) {
    Write-Host "Primeira execucao (sem estado salvo): a decisao sera pela cobertura real do cache." -ForegroundColor Yellow
}
else {
    Write-ItemList "Bundles adicionados" $diff.Added "Magenta"
    Write-ItemList "Bundles alterados" $diff.Changed "Magenta"
    Write-ItemList "Bundles removidos" $diff.Removed "Yellow"
    if ($diff.Added.Count + $diff.Changed.Count + $diff.Removed.Count -eq 0) {
        Write-Host "  Nenhuma mudanca de bundles desde a ultima execucao." -ForegroundColor Green
    }
}

# Changed bundles: the cached copy may be stale even with identical size, so it must be
# invalidated (deleted) to force the client to re-download it.
$invalidateRels = @()
foreach ($k in $diff.Changed) {
    $idx = $k.IndexOf("/bundles/")
    if ($idx -ge 0) { $invalidateRels += $k.Substring($idx + 9) }
}

$orphans = @(Get-OrphanCacheFiles $expectedCache $CacheBundlesPath)

# A gap that is in knownMissing already failed a warmup before - don't reopen the game for
# it every run. But if its source bundle changed, it deserves a fresh attempt.
$retryRels = @()
foreach ($k in ($diff.Added + $diff.Changed)) {
    $idx = $k.IndexOf("/bundles/")
    if ($idx -ge 0) { $retryRels += $k.Substring($idx + 9) }
}
$knownMissing = @($knownMissing | Where-Object { $retryRels -notcontains $_ })

# =====================================================================
# 2. Check-only mode: report and exit before any mutation
# =====================================================================

if ($CheckOnly) {
    Write-Host "`n--- RELATORIO (CHECK-ONLY) ---" -ForegroundColor Cyan
    Write-ItemList "Copias de cache que seriam invalidadas (bundle alterado)" $invalidateRels "Yellow"
    Write-ItemList "Orfaos que seriam removidos do cache" @($orphans | ForEach-Object { $_.FullName }) "Yellow"

    $simulatedGaps = @(Get-CacheGaps $expectedCache $CacheBundlesPath)
    $simulatedGaps = @($simulatedGaps + $invalidateRels | Sort-Object -Unique)
    $simulatedNew = @($simulatedGaps | Where-Object { $knownMissing -notcontains $_ })
    Write-ItemList "Bundles sem copia valida no cache (gaps)" $simulatedNew "Magenta"

    if ($simulatedNew.Count -gt 0) {
        Write-Host "`nDECISAO: o jogo SERIA aberto ($($simulatedNew.Count) bundle(s) a gerar)." -ForegroundColor Magenta
    }
    else {
        Write-Host "`nDECISAO: o jogo NAO seria aberto (cache 3D completo)." -ForegroundColor Green
    }
    Write-Host "Check-only: encerrando sem robocopy e sem watcher." -ForegroundColor Yellow
    exit 0
}

# =====================================================================
# 3. Cache maintenance without the game (invalidation + orphan cleanup)
# =====================================================================

foreach ($rel in $invalidateRels) {
    $p = Join-Path $CacheBundlesPath ($rel.Replace('/', '\'))
    if (Test-Path $p) {
        Remove-Item -LiteralPath $p -Force -ErrorAction SilentlyContinue
        Write-Host "  Cache invalidado (bundle alterado): $rel" -ForegroundColor Yellow
    }
}

if ($orphans.Count -gt 0) {
    Write-Host "Removendo $($orphans.Count) bundle(s) orfao(s) do cache (origem removida dos mods)..." -ForegroundColor Yellow
    foreach ($f in $orphans) {
        Remove-Item -LiteralPath $f.FullName -Force -ErrorAction SilentlyContinue
    }
    # Prune now-empty directories (deepest first)
    Get-ChildItem -Path $CacheBundlesPath -Recurse -Directory -ErrorAction SilentlyContinue |
        Sort-Object { $_.FullName.Length } -Descending |
        Where-Object { @(Get-ChildItem -Path $_.FullName -Force -ErrorAction SilentlyContinue).Count -eq 0 } |
        Remove-Item -Force -ErrorAction SilentlyContinue
}

# =====================================================================
# 4. Open the game ONLY if some bundle has no valid cache copy
# =====================================================================

$gaps = @(Get-CacheGaps $expectedCache $CacheBundlesPath)
$newGaps = @($gaps | Where-Object { $knownMissing -notcontains $_ })

if ($newGaps.Count -gt 0) {
    Write-Host "`nCache 3D incompleto: $($newGaps.Count) bundle(s) precisam ser gerados pelo cliente." -ForegroundColor Magenta
    Write-ItemList "Bundles a gerar" $newGaps "Magenta"

    $warmupOk = Invoke-GameCacheWarmup

    if ($warmupOk) {
        $gapsAfter = @(Get-CacheGaps $expectedCache $CacheBundlesPath)
        if ($gapsAfter.Count -gt 0) {
            Write-Host "AVISO: $($gapsAfter.Count) bundle(s) continuam sem copia no cache apos o warmup." -ForegroundColor Yellow
            Write-Host "Eles serao baixados in-game pelos jogadores (fallback normal do SPT)." -ForegroundColor Yellow
            Write-ItemList "Ainda faltando" $gapsAfter "Yellow"
        }
        else {
            Write-Host "Cache 3D completo apos o warmup." -ForegroundColor Green
        }
        Save-State $currentBundles $gapsAfter
    }
    else {
        Write-Host "AVISO: warmup falhou. Estado NAO atualizado; nova tentativa na proxima execucao." -ForegroundColor Red
    }
}
else {
    if ($gaps.Count -gt 0) {
        Write-Host "Cache 3D com $($gaps.Count) pendencia(s) ja conhecida(s) (knownMissing); jogo nao sera aberto." -ForegroundColor Yellow
    }
    else {
        Write-Host "Cache 3D completo. Pulando abertura do jogo." -ForegroundColor Green
    }
    # Keep only entries that are still real gaps, so resolved ones stop being tracked
    Save-State $currentBundles @($knownMissing | Where-Object { $gaps -contains $_ })
}

# =====================================================================
# 5. Mirror cache -> Launcher-Updater (always, so deletions propagate too)
# =====================================================================

Write-Host "`n--- SINCRONIZANDO PASTAS DE CACHE ---" -ForegroundColor Yellow
Write-Host "De: $ServerCachePath"
Write-Host "Para: $UpdaterCachePath"

if (!(Test-Path $UpdaterCachePath)) {
    New-Item -ItemType Directory -Force -Path $UpdaterCachePath | Out-Null
}

# /MIR mirror tree (copy new/changed, delete vanished)
# /FFT FAT file times (safer comparison on Windows)
# /R:2 /W:5 fail fast on locked files (default is 1M retries x 30s = script hangs forever)
# /NDL /NJH /NJS /NP quiet output, only copied file names
robocopy $ServerCachePath $UpdaterCachePath /MIR /FFT /R:2 /W:5 /NDL /NJH /NJS /NP

$roboExit = $LASTEXITCODE
# Robocopy: 0-7 = success variants; 8+ = errors
if ($roboExit -ge 8) {
    Write-Host "ALERTA: Ocorreram erros durante a sincronizacao pelo Robocopy! (exit $roboExit)" -ForegroundColor Red
}
else {
    Write-Host "Sincronizacao do cache concluida com sucesso!" -ForegroundColor Green
}
Write-Host "---------------------------------------"

# =====================================================================
# 6. Production watcher loop
# =====================================================================

Write-Host "`n--- INICIANDO SERVIDOR SPT (MODO PRODUCAO) ---" -ForegroundColor Magenta
$WaitTime = 5

while ($true) {
    Write-Host "[$(Get-Date -Format 'HH:mm:ss')] Iniciando Servidor..." -ForegroundColor Green

    # Start and block until it exits
    Start-Process -FilePath $ServerExePath -WorkingDirectory $ServerPath -Wait

    Write-Host "[$(Get-Date -Format 'HH:mm:ss')] Servidor fechou! Reiniciando em $WaitTime segundos..." -ForegroundColor Yellow
    Start-Sleep -Seconds $WaitTime
}
